version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    depends_on:
      - oauth
    ports:
      - 23456:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  oauth:
    restart: unless-stopped
    image: quay.io/oauth2-proxy/oauth2-proxy
    environment:
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_REVERSE_PROXY=1
      - OAUTH2_PROXY_UPSTREAMS=http://web:8080
      - OAUTH2_PROXY_COOKIE_REFRESH=${OAUTH2_PROXY_COOKIE_REFRESH}
      - OAUTH2_PROXY_COOKIE_DOMAINS=${OAUTH2_PROXY_COOKIE_DOMAINS}
      - OAUTH2_PROXY_COOKIE_NAME=${OAUTH2_PROXY_COOKIE_NAME}
      - OAUTH2_PROXY_COOKIE_SAMESITE=${OAUTH2_PROXY_COOKIE_SAMESITE}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
      - OAUTH2_PROXY_AUTHENTICATED_EMAILS_FILE=/etc/oauth2-proxy/authenticated-emails.txt
    depends_on:
      - web
    volumes:
      - ./authenticated-emails.txt:/etc/oauth2-proxy/authenticated-emails.txt
  web:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./.open-webui:/app/backend/data
