version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    depends_on:
      - oauth
    ports:
      - 12345:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  oauth:
    restart: unless-stopped
    image: quay.io/oauth2-proxy/oauth2-proxy
    environment:
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_REVERSE_PROXY=1
      - OAUTH2_PROXY_UPSTREAMS=http://web:3000
      - OAUTH2_PROXY_COOKIE_REFRESH=${OAUTH2_PROXY_COOKIE_REFRESH}
      - OAUTH2_PROXY_COOKIE_DOMAINS=${OAUTH2_PROXY_COOKIE_DOMAINS}
      - OAUTH2_PROXY_COOKIE_NAME=${OAUTH2_PROXY_COOKIE_NAME}
      - OAUTH2_PROXY_COOKIE_SAMESITE=${OAUTH2_PROXY_COOKIE_SAMESITE}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
      - OAUTH2_PROXY_AUTHENTICATED_EMAILS_FILE=/etc/oauth2-proxy/authenticated-emails.txt
    depends_on:
      - web
    volumes:
      - ./authenticated-emails.txt:/etc/oauth2-proxy/authenticated-emails.txt
  copilot:
    image: aaamoon/copilot-gpt4-service:latest
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - CACHE=true
      - CACHE_PATH=/var/copilot-gpt4-service/cache.sqlite3
      - COPILOT_TOKEN=${COPILOT_TOKEN}
    volumes:
      - ./.cache:/var/copilot-gpt4-service
  web:
    build:
      context: ./ChatGPT-Next-Web
    restart: unless-stopped
    depends_on:
      - copilot
    environment:
      - BASE_URL=http://copilot:8080
